optimus/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import login, logout, register
from api.account.views import LoginViewSet, GetAllAPIView, GetConfigAPIView
from api.mission.views import MissionAPIView, MissionPrognosticsAPIView
from api.vehicle.views import VehicleAPIView
from .views import schema_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),

    # REST API
    path('api/login/', LoginViewSet.as_view({'post': 'create'}), name='api-login'),
    path('api/get-all/', GetAllAPIView.as_view(), name='api-get-all'),
    path('api/docs/', schema_view, name='api-docs'),
    path('api/mission/<int:pk>', MissionAPIView.as_view({'get': 'retrieve'}), name='mission-id'),
    path('api/mission/', MissionAPIView.as_view({'get': 'list'}), name='mission-list'),
    path('api/mission/<int:pk>/prognostics', MissionPrognosticsAPIView.as_view(), name='mission-prognostics'),
    path('api/vehicle/', VehicleAPIView.as_view(), name='vehicle-list'),
    path('api/config/', GetConfigAPIView.as_view(), name='config'),

    path('supervision/', include("supervision.urls")),
    path('', include("web_app.urls")),
]

web_app/urls.py
from django.urls import path
from django.contrib import admin

from web_app.views.mission import MissionListView, MissionDetailView
from web_app.views.report import ReportView, generate_report
from web_app.views.vehicle import VehicleView
from web_app.views.prognosis import PrognosisView


urlpatterns = [
    path('', MissionListView.as_view(), name='mission_list'),
    path('mission/<int:pk>', MissionDetailView.as_view(), name='mission'),
    path('mission/<int:pk>/report', ReportView.as_view(), name='report'),
    path('vehicle/<int:pk>', VehicleView.as_view(), name='vehicle'),
    path('report/<int:pk>', generate_report, name='mission_report'),
    path('prognosis/', PrognosisView.as_view(), name='mission prognosis'),
]

admin.site.site_header = 'Optimus - Admin'

web_app/models.py
import math
from datetime import date

from django.db import models
from autoslug import AutoSlugField

from account.models import Profile


#  depricated (maybe???)
class Environment(models.Model):
    # id uuid NOT NULL,
    name = models.CharField(max_length=200)
    time = models.BigIntegerField()
    value = models.BigIntegerField()

    class Meta:
        db_table = "env"


# depricated (maybe???)
class System(models.Model):
    # id uuid NOT NULL,
    name = models.CharField(max_length=200)
    time = models.BigIntegerField()
    value = models.BigIntegerField()

    class Meta:
        db_table = "sys"


class SubSystem(models.Model):
    """ Subassy type, element of a vehicle_type. Example: battery, engine, braking system """
    name = models.CharField(max_length=200)
    vehicle_type = models.ForeignKey('VehicleType', on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "sub_sys"

    def __str__(self):
        return self.name


class ConcreteSubSystem(models.Model):
    """ Concrete subassy of a concrete vehicle """
    subsystem = models.ForeignKey('SubSystem', on_delete=models.CASCADE)
    vehicle = models.ForeignKey('Vehicle', related_name='subassies', on_delete=models.CASCADE)
    health = models.DecimalField('Current Health', max_digits=5, decimal_places=1)

    class Meta:
        db_table = "concrete_sub_sys"

    def __str__(self):
        return '{} - {}'.format(self.vehicle.name, self.subsystem.name)


class Sensor(models.Model):
    """ Example: Speed, Calculated engine load, Intake air temperature, Throttle position """
    subsystem = models.ForeignKey(SubSystem, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name', always_update=True, unique=True, null=True)
    obd_code = models.CharField(max_length=50, null=True, blank=True)
    unit = models.CharField('Unit of Measurement', max_length=50, null=True, blank=True)
    lower_bound = models.DecimalField('Lower bound of warning threshold', max_digits=9, decimal_places=6, default=0.0)
    upper_bound = models.DecimalField('Upper bound of warning threshold', max_digits=9, decimal_places=6, default=100.0)

    class Meta:
        db_table = "sensor"

    def __str__(self):
        return self.name


class Mission(models.Model):
    """ Transport mission to deliver a cargo from one point to another """
    # todo: move Points to separate entity
    departure_point = models.CharField(max_length=200)
    arrival_point = models.CharField(max_length=200)
    departure_long = models.DecimalField('Departure Longitude', max_digits=9, decimal_places=6, null=True, blank=True)
    departure_lat = models.DecimalField('Departure Latitude', max_digits=9, decimal_places=6, null=True, blank=True)
    arrival_long = models.DecimalField('Arrival Longitude', max_digits=9, decimal_places=6, null=True, blank=True)
    arrival_lat = models.DecimalField('Arrival Latitude', max_digits=9, decimal_places=6, null=True, blank=True)
    started_at = models.DateTimeField('Planned Start Time', null=True, blank=True)
    ended_at = models.DateTimeField('Planned Finish Time', null=True, blank=True)
    actual_end_at = models.DateTimeField('Actual Finish Time', null=True, blank=True)

    class Meta:
        db_table = "mission"

    def __str__(self):
        return self.name

    @property
    def status(self):
        if self.ended_at and (date.today() > self.ended_at.date()):
            return 'Finished'
        elif self.started_at and (date.today() < self.started_at.date()):
            return 'Planned'
        else:
            return 'Active'

    @property
    def name(self):
        return '{} - {}'.format(self.departure_point, self.arrival_point)

    @property
    def distance(self):
        a = round(
            math.sqrt(
                ((self.arrival_lat - self.departure_lat) * (self.arrival_lat - self.departure_lat)) +
                ((self.arrival_long - self.departure_long) * (self.arrival_long - self.departure_long))
            )
            , 2)

        return a * 12.5

    @property
    def delay_abs(self):
        """ Mission delay in hours. """
        if self.ended_at and self.actual_end_at:
            delta = self.actual_end_at - self.ended_at
            hours, remainder = divmod(delta.seconds, 3600)
            hours = delta.days * 24 + hours
            return hours
        else:
            return None

    @property
    def delay_percentage(self):
        """ Mission delay in percents. """
        if self.delay_abs and self.started_at:
            planned_delta = self.ended_at - self.started_at
            planned_hours, remainder = divmod(planned_delta.seconds, 3600)
            print(planned_hours, remainder)
            delay_percentage = self.delay_abs / (planned_delta.days * 24 + planned_hours) * 100
            return round(delay_percentage, 1)
        else:
            return None


class VehicleType(models.Model):
    """ Vehicle type (truck, four-wheeler) """
    name = models.CharField(max_length=200)

    class Meta:
        db_table = "vehicle_type"

    def __str__(self):
        return self.name


class Vehicle(models.Model):
    """ Concrete vehicle """
    AVAILABLE = 'AVAILABLE'
    MAINTENANCE = 'MAINTENANCE'
    RESERVED = 'RESERVED'
    MISSION = 'MISSION'
    STATUSES = (
        (AVAILABLE, 'Available'),
        (MAINTENANCE, 'In maintenance'),
        (RESERVED, 'Reserved for mission'),
        (MISSION, 'In mission'),
    )
    status = models.CharField(max_length=100, choices=STATUSES, default=AVAILABLE)
    mission = models.ForeignKey(Mission, related_name='vehicles', on_delete=models.CASCADE, null=True, blank=True)
    driver = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    type = models.ForeignKey(VehicleType, verbose_name='Vehicle Type', on_delete=models.CASCADE, null=True)
    current_location = models.CharField(max_length=200, default='Main Station')
    last_maintenance = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        db_table = "vehicle"

    def __str__(self):
        return self.name

    @property
    def last_mission_point(self):
        return self.missionpoint_set.order_by('timestamp').first()


# depricated
class SensorsData(models.Model):
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    time = models.BigIntegerField()
    value = models.BigIntegerField()

    class Meta:
        db_table = "sensors_data"


class MissionPoint(models.Model):
    timestamp = models.BigIntegerField()
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    long = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True)
    lat = models.DecimalField(
        max_digits=9, decimal_places=6, null=True, blank=True)
    alt = models.BigIntegerField()

    class Meta:
        db_table = "mission_point"

    @property
    def warning_sensor_list(self):
        return ', '.join(self.missionpointsensorsdata_set.filter(
            warning=True).values_list('slug', flat=True))

class MissionPointSensorsData(models.Model):
    mission_point = models.ForeignKey(MissionPoint, on_delete=models.CASCADE)
    slug = models.CharField(max_length=255, default='')
    warning = models.BooleanField(default=False)
    value = models.CharField(max_length=255, default='')

    class Meta:
        db_table = "mission_point_sensors_data"

api/mission/views.py
import random

from django.db.models import Q
from rest_framework import viewsets
from rest_framework.generics import RetrieveAPIView
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
import dateutil.parser

from api.mission.serializers import (
    MissionDetailedSerializer, MissionSerializer, MissionPrognosticsSerializer)
from api.vehicle.serializers import VehicleSerializer
from web_app.models import Mission, Vehicle


class MissionAPIView(ListModelMixin, RetrieveModelMixin,
                     viewsets.GenericViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = MissionSerializer
    queryset = Mission.objects.all()

    def retrieve(self, request, *args, **kwargs):
        self.serializer_class = MissionDetailedSerializer
        return super(MissionAPIView, self).retrieve(
            request, *args, **kwargs)


class MissionPrognosticsAPIView(RetrieveAPIView):
    """ For Carlos prognostics page.\n
    Response data format: {"data": [{
            "driver_name": "Walter Nosiglia",
            "name": "Mercedez",
            "type":"Truck",
            "position": "Bolivia",
            "maitenance": "20/02/1999",
            "engine_diagnosis": "40",
            "engine_prognosis": "10",
            "fuel_system_diagnosis": "30",
            "fuel_system_prognosis": "10",
            "battery_diagnosis": "47",
            "battery_prognosis": "27",
            "in_mission":"1"
    }]}
    """
    permission_classes = (IsAuthenticated,)
    renderer_classes = (JSONRenderer,)
    serializer_class = MissionPrognosticsSerializer
    queryset = Mission.objects.all()

    def retrieve(self, request, *args, **kwargs):
        result = []
        vehicles_available = Vehicle.objects.filter(Q(status='AVAILABLE') | Q(mission_id=self.kwargs['pk'])).all()
        serializer_available = VehicleSerializer(vehicles_available, many=True)
        vehicles = serializer_available.data
        for vehicle in vehicles:
            v_data = {}
            v_data['id'] = vehicle['id']
            v_data['driver_name'] = vehicle.get('driver', '')
            v_data['name'] = vehicle['name']
            v_data['type'] = vehicle.get('type', '')
            v_data['position'] = vehicle['current_location']
            v_data['maitenance'] = dateutil.parser.parse(vehicle['last_maintenance']).strftime('%d/%m/%Y')
            v_data['in_mission'] = 1 if vehicle.get('mission', '') == self.kwargs['pk'] else 0
            subassies = vehicle['subassies']
            for sub in subassies:
                v_data[sub['name'].lower().replace(' ', '_') + '_diagnosis'] = float(sub['health'])
                v_data[sub['name'].lower().replace(' ', '_') + '_prognosis'] = random.randint(0, float(sub['health']))
            result.append(v_data)
        return Response({'data': result})

api/vehicle/views.py
from collections import defaultdict

import django_filters
from rest_framework.permissions import IsAuthenticated
from rest_framework.generics import ListAPIView

from api.vehicle.serializers import VehicleSerializer
from web_app.models import Vehicle


class VehicleAPIView(ListAPIView):
    """ 
    Get list of vehicles for a mission, driver, type (optional)\n
    http://example.com/api/vehicle?mission=1
    """
    permission_classes = (IsAuthenticated,)
    serializer_class = VehicleSerializer
    queryset = Vehicle.objects.all()
    filter_backends = (django_filters.rest_framework.DjangoFilterBackend,)
    filter_fields = ('mission', 'driver', 'type')

web_app/views/mission.py
# coding: utf-8
from django.views.generic import ListView, DetailView

from web_app.models import Mission, Vehicle


class MissionListView(ListView):
    template_name = "mission_list.html"
    model = Mission


class MissionDetailView(DetailView):
    template_name = "mission.html"
    model = Mission

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['vehicle_list'] = Vehicle.objects.filter(mission=self.kwargs['pk']).select_related('type')

        return context

web_app/views/prognosis.py
# coding: utf-8
from django.views.generic import ListView , DetailView

from web_app.models import Vehicle, Mission


class PrognosisView(ListView):
    template_name = "prognosis.html"
    model = Vehicle

    
class MissionDetailView(DetailView):
    template_name = "mission.html"
    model = Mission

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['vehicle_list'] = Vehicle.objects.filter(mission=self.kwargs['pk']).select_related('type')

        return context

web_app/views/report.py
# coding: utf-8
import os
from docxtpl import DocxTemplate
from django.http.response import HttpResponse
from django.views.generic import ListView

from web_app.models import Vehicle, Mission


class ReportView(ListView):
    template_name = "report.html"
    model = Mission

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['object'] = Mission.objects.get(pk=self.kwargs['pk'])

        context['object_list'] = Vehicle.objects.filter(
            mission=self.kwargs['pk']
        ).select_related('type')

        return context


def generate_report(request, pk):
    path = os.path.join(os.path.abspath(os.path.curdir), "report.docx")
    doc = DocxTemplate(path)

    mission = Mission.objects.get(id=pk)

    vehicles = Vehicle.objects.filter(
        mission=pk
    ).select_related('type')

    for i, veh in enumerate(vehicles):
        veh.distance = mission.distance
        veh.average_speed = 70 if i == 0 else 74
        veh.fuel = 240.3 if i == 0 else 300.7

    result = {'mission_name': mission.name,
              'arrival_point': mission.arrival_point,
              'departure_point': mission.departure_point,
              'started_at': mission.started_at.date(),
              'ended_at': mission.ended_at.date(),
              'vehicle': vehicles,
              }

    doc.render(result)
    doc.save("generated_doc.docx")
    with open("generated_doc.docx", 'rb') as fh:
        response = HttpResponse(fh.read(), content_type="application/msword")
        response['Content-Disposition'] = 'inline; filename=generated_doc.docx'
        return response

web_app/views/vehicle.py
# coding: utf-8
from django.views.generic import DetailView

from web_app.models import Vehicle, Mission


class VehicleView(DetailView):
    template_name = "vehicle.html"
    model = Vehicle

web_app/views/weather.py
# coding: utf-8
import datetime

from django.views.generic import TemplateView
from prognostics.weather import Weather

class WeatherView(TemplateView):
    template_name = "weather.html"

    def get(self, *args, **kwargs):
        lat = 55.751716
        lon = 48.747310
        today = datetime.date.today()
        
        kwargs['weather'] = Weather.get_weather(lat, lon, today)

        return super().get(*args, **kwargs)

web_app/templates/footer_base.html
{% load static %}
<!--This is the footer, if needed we can change it and use it as template-->
	<section class="footer">
		<div class="text-center">
			<div class="row">
				<div class="col-12">Optimus & Martlet Alliance copyright | 2018</div>
			</div>
		</div>
	</section>

web_app/templates/procurement.html
{% extends "web_app_base.html" %}
{% load static %}

{% block content %}
    <div class="" style="display:block; width: 70%; margin: auto;">
        <div class="panel" id="spy2">
            <div class="panel-body pn">
                <h3 style="margin-top: 50px">Subassy procurement planning
                    for vehicle {{ vehicle.name }}</h3>
            <br>

            {% for ss in subsystems %}
                <hr>
                <h5>Subsystem: {{ ss.name }}</h5>
                Procurement: <input type="checkbox" name="" id="">
                <br><br>

                <table class="table footable" data-filter="#fooFilter">
                    <thead>
                    <tr>
                        <th style="width: 50%">Sensor name</th>
                        <th>Slug</th>
                        <th>Is warning</th>
                    </tr>
                    </thead>
                    {% for sensor in ss.sensor_set.all %}
                        <tr>
                            <td>{{ sensor.name }}</td>
                            <td>{{ sensor.slug }}</td>

                            <td>
                                {% if vehicle.last_mission_point and sensor.slug in vehicle.last_mission_point.warning_sensor_list %}
                                        +


                                {%  endif %}

                                </td>
                        </tr>
                    {% endfor %}
                </table>

            {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

web_app/templates/vehicle.html
{% extends "web_app_base.html" %} 

{% block title %}
<title>Optimus - Vehicle Data</title>
{% endblock title %} 

<!--Loading static library if needed-->
{% load static %} 

<!--Here we start with the content of the page-->
{% block content %} 

<!--Here we implemented security-->
{% if user.is_authenticated %}
<img src="{% static 'svg/truck-6.svg' %}" alt=""> {% for subassy in object.type.subsystem_set.all %}
<h2>{{ subassy }}</h2>
<table id="appendable" style="width: 80%; margin: auto;">
    <tr>
        {% for sensor in subassy.sensor_set.all|slice:":3" %}
        <td>
            <div class="panel" id="{{ sensor.slug }}" style="display: block;">
                <div class="panel-heading" style="display: block;">
                    <span class="panel-icon">
                <i class="fa fa-area-chart"></i>
              </span>
                    <span class="panel-title">{{ sensor.name }}</span>
                </div>
                <div class="panel-body bg-light dark" style="display: block;">
                    <div id="zoom-{{ sensor.slug }}" style="height: 100%; width: 100%;"></div>
                </div>
            </div>
        </td>
        {% endfor %}
    </tr>
<tr>
        {% for sensor in subassy.sensor_set.all|slice:"3:6" %}
        <td>
            <div class="panel" id="{{ sensor.slug }}" style="display: block;">
                <div class="panel-heading" style="display: block;">
                    <span class="panel-icon">
                <i class="fa fa-area-chart"></i>
              </span>
                    <span class="panel-title">{{ sensor.name }}</span>
                </div>
                <div class="panel-body bg-light dark" style="display: block;">
                    <div id="zoom-{{ sensor.slug }}" style="height: 100%; width: 100%;"></div>
                </div>
            </div>
        </td>
        {% endfor %}
    </tr>
<tr>
        {% for sensor in subassy.sensor_set.all|slice:"6:9" %}
        <td>
            <div class="panel" id="{{ sensor.slug }}" style="display: block;">
                <div class="panel-heading" style="display: block;">
                    <span class="panel-icon">
                <i class="fa fa-area-chart"></i>
              </span>
                    <span class="panel-title">{{ sensor.name }}</span>
                </div>
                <div class="panel-body bg-light dark" style="display: block;">
                    <div id="zoom-{{ sensor.slug }}" style="height: 100%; width: 100%;"></div>
                </div>
            </div>
        </td>
        {% endfor %}
    </tr>
</table>

{% endfor %} 
{% endif %} 

{% endblock content %} 
{% block scripts %}

<!-- Page Plugins -->
<script src="{% static 'vendor/plugins/c3charts/d3.min.js' %}"></script>
<script src="{% static 'vendor/plugins/c3charts/c3.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<!-- Page Javascript -->
<script src="{% static 'assets/js/demo/charts/d3.js' %}"></script>

<!--<script type="text/javascript">-->
<!--jQuery(document).ready(function () {-->


<!--// This page contains more Initilization Javascript than normal.-->
<!--// As a result it has its own js page. See charts.js for more info-->
<!--//D3Charts.init();-->


<!--});-->
<!--</script>-->


<script>
    var BigObject = {};

    /* All functions in this file are used only for charts.html */
    var D3Charts = function() {

        var runD3Plugins = function() {

        }

        // Init Flot Charts Plugin
        var runD3Charts = function() {

            {% for subassy in object.type.subsystem_set.all %}
            {%                for sensor in subassy.sensor_set.all %}

            // Add a series of colors to be used in the charts and pie graphs
            var Colors = [bgPrimary, bgInfo, bgWarning, bgAlert, bgDanger, bgSystem, bgSuccess, ];
            <!--var values = ['t'].concat(-->
            <!--document.getElementById('zoom-{{ sensor.slug }}').dataset.values.split(',')-->
            <!--);-->
            <!--console.log("values");-->
            <!--console.log(values);-->

            //console.log("{{ sensor.slug }}");
            //console.log(BigObject["{{ sensor.slug }}"]);
            // MouseWheel Zoom

            try {
                var chart9 = c3.generate({
                    bindto: '#zoom-{{ sensor.slug }}',
                    color: {
                        pattern: Colors,
                    },
                    padding: {
                        left: 30,
                        right: 15,
                        top: 0,
                        bottom: 0,
                    },
                    data: {
                        columns: [
                            ["UNIT"].concat(BigObject["{{ sensor.slug }}"])
                        ]
                    },
                    zoom: {
                        enabled: true
                    }
                });
            } catch (error) {

                console.error(error);
                document.getElementById('{{ sensor.slug }}').style.display = "none";
            }

            {% endfor %} {% endfor %}


            // Donut Chart
            var chart10 = c3.generate({
                bindto: '#donut-chart',
                color: {
                    pattern: Colors,
                },
                data: {
                    columns: [
                        ['data1', 10],
                        ['data2', 120],
                    ],
                    type: 'donut',
                    onclick: function(d, i) {
                        console.log("onclick", d, i);
                    },
                    onmouseover: function(d, i) {
                        console.log("onmouseover", d, i);
                    },
                    onmouseout: function(d, i) {
                        console.log("onmouseout", d, i);
                    }
                },
                donut: {
                    title: "The overall 111"
                }
            });

        };
        return {
            init: function() {
                runD3Plugins();
                runD3Charts();
            }
        };
    }();


    //<!--SOME LOGICAL DIVIDER-->
    var slice_val = 75;
    // some sample json to graph processor
    //SpeedObject.push()
    function get_params(some_object) {


        for (var key in some_object["sensors"]) {
            if (some_object["sensors"].hasOwnProperty(key)) {
                //console.log(key + " -> " + some_object["sensors"][key]);
                if (isEmpty(BigObject)) {
                    BigObject[key] = [];
                }
                if (!BigObject.hasOwnProperty(key)) {
                    BigObject[key] = [];
                }
                var current_val = parseFloat(some_object["sensors"][key]);
                if (isNaN(current_val))
                    current_val = 0;
                BigObject[key].push(current_val);
                if (BigObject[key].length > slice_val) {
                    BigObject[key] = BigObject[key].slice(-slice_val);
                }
                //slug_to_array_append(key, some_object["sensors"][key]);
                //console.log(BigObject);
            }
        }
    }

    function isEmpty(obj) {
        for (var prop in obj) {
            if (obj.hasOwnProperty(prop))
                return false;
        }

        return JSON.stringify(obj) === JSON.stringify({});
    }


    function table_appender(json_object) {
        var table = document.getElementById("appendable");
        var table_row = 0;
        var row = table.insertRow(table_row);


        var current_cell = 0;
        var table_content = "";
        var cell = row.insertCell(current_cell);

        for (var key in json_object["sensors"]) {
            if (json_object["sensors"].hasOwnProperty(key)) {
                console.log(key + " -> " + json_object["sensors"][key]);
                table_content = "<div class='panel' id='";
                table_content += key; //some_id_named_after
                table_content += "'><div class='panel-heading'><span class='panel-icon'><i class='fa fa-area-chart'></i></span><span class='panel-title'>";
                table_content += key; //some_title
                table_content += "</span></div><div class='panel-body bg-light dark'><div id='";
                table_content += key; //some_id
                table_content += "' style='height: 370px; width: 100%;'></div></div></div>";
                if (current_cell >= 1) {
                    current_cell = 0;
                    table_row += 1;
                    row = table.insertRow(table_row);
                } else {
                    current_cell += 1;
                }
                cell = row.insertCell(current_cell);
                cell.innerHTML = table_content;
            }
        }


        //MQQT starts here
        
        
        // Create a client instance
        function MQTTconnect() {
            // Create a client instance
            client = new Paho.MQTT.Client("35.189.64.191", 8083, "clientId");



            //<!--cell1.innerHTML = table_content;-->
            //<!--cell2.innerHTML = table_content;-->
        }



        // Create a client instance
        function MQTTconnect(host, port) {
            // Create a client instance
            console.log(typeof(port));
            // client = new Paho.MQTT.Client(host, port, "clientId");

            client = new Paho.MQTT.Client(host, port, "clientId");

            // set callback handlers
            client.onConnectionLost = onConnectionLost;
            client.onMessageArrived = onMessageArrived;

            // connect the client
            client.connect({
                onSuccess: onConnect
            });
        }

        // called when the client connects
        function onConnect() {
            // Once a connection has been made, make a subscription and send a message.
            console.log("onConnect");
            client.subscribe("test");
        }

        // called when the client loses its connection
        function onConnectionLost(responseObject) {
            if (responseObject.errorCode !== 0) {
                console.log("onConnectionLost:" + responseObject.errorMessage);

                sample_obj = {
                    "timestamp": 1523383353535,
                    "mission_id": 1,
                    "vehicle_id": 1,
                    "location": {
                        "lat": 55.735448203694574,
                        "lon": 48.780123124119626,
                        "alt": 104
                    },
                    "sensors": {
                        "speed": "85.78299711970612km\\/h",
                        "barometric_pressure": "98kPa",
                        "engine_coolant_temp": "96C",
                        "fuel-level": "NODATA",
                        "engine_load": "31,8%",
                        "ambient_air_temp": "9C",
                        "engine-rpm": "748RPM",
                        "intake_manifold_pressure": "NODATA",
                        "maf": "3,66g\\/s",
                        "long-term-fuel-trim-bank-2": "NODATA",
                        "fuel-type": "NODATA",
                        "air_intake_temp": "28C",
                        "fuel-pressure": "NODATA",
                        "short-term-fuel-trim-bank-2": "NODATA",
                        "short-term-fuel-trim-bank-1": "-2,3%",
                        "engine-runtime": "00:17:07",
                        "throttle-pos": "12,9%",
                        "dtc-number": "MIL is OFF0 codes",
                        "trouble-codes": "C0300\n",
                        "timing-advance": "59,6%",
                        "equiv-ratio": "1,0%"
                    },
                    "road_condition": {
                        "highway": "trunk",
                        "int_ref": "E 22",
                        "lanes": "2",
                        "lit": "yes",
                        "maxspeed": "90",
                        "ref": "\u041c-7",
                        "surface": "asphalt"
                    }
                };
                console.log(sample_obj);
                table_appender(sample_obj);
                get_params(sample_obj);

                D3Charts.init();

            }
            setTimeout(MQTTconnect, 2000);
        }

        // called when a message arrives
        function onMessageArrived(message) {
            console.log("onMessageArrived:" + message.payloadString);
            obj = JSON.parse(message.payloadString);
            get_params(obj);
            D3Charts.init();
        }
        httpGetAsync("http://" + myhost + "/api/config/", write_to_config);

</script>


{% endblock scripts %}